### ISSUE TITLE
[Docs]: update termux-x11 docs

### ISSUE THREAD

**Issue by SaicharanKandukuri** [RandomCoderOrg/udroid-wiki#8]

**Comment by twaik** [comment]
I agree, termux-x11 docs here are pretty much outdated.

**Comment by SaicharanKandukuri** [comment]
> I agree, termux-x11 docs here are pretty much outdated.

Guess I couldn't keep up with the termux-x11 development speed

**Comment by twaik** [comment]
https://github.com/ivon852/netlify-ivon-blog-comments/discussions/475#discussioncomment-6612958 I've stated the main points here.

**Comment by SaicharanKandukuri** [comment]
> [ivon852/netlify-ivon-blog-comments#475 (reply in thread)](https://github.com/ivon852/netlify-ivon-blog-comments/discussions/475#discussioncomment-6612958) I've stated the main points here.

Thanks for that @twaik 
I'll rewrite the wiki pages soon :+1:
